"""bracket support nullable teams

Revision ID: 1e38cb203a10
Revises: 31d27c5ce800
Create Date: 2026-02-07 07:01:50.646260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e38cb203a10'
down_revision = '31d27c5ce800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bracket_position', sa.Integer(), nullable=True))
        batch_op.alter_column('home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('bracket_position')

    # ### end Alembic commands ###
