"""add penalty_winner_id to matches

Revision ID: 805b7f8a9466
Revises: 1e38cb203a10
Create Date: 2026-02-08 02:37:24.124171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805b7f8a9466'
down_revision = '1e38cb203a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_winner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_matches_penalty_winner', 'teams', ['penalty_winner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matches_penalty_winner', type_='foreignkey')
        batch_op.drop_column('penalty_winner_id')

    # ### end Alembic commands ###
