"""add avatar_url to users

Revision ID: 971396ee79ab
Revises: 805b7f8a9466
Create Date: 2026-02-11 03:27:19.093421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971396ee79ab'
down_revision = '805b7f8a9466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
